chore(http-client): Add timeout for http client
inloco/go-fcm pull request #1
Opened 2020-05-27 19:36 UTC by foolOnTheHill

**Purpose**

Improve `http.Client` to configure timeout for it's connections.

2020-05-27 19:39 UTC, ottony commented on fcm.go
> +			MaxConnsPerHost:     0,
Tu pode me explicar pq zero?

2020-05-27 19:40 UTC, figueredo reviewed
Boa! O que acha de atualizar o fork com o original antes de subir esse PR? Tem coisa nova no fcm.go (não analisei o que era).

2020-05-27 19:41 UTC, ottony commented on fcm.go
> +		Timeout: 1 * time.Second,
Essa lib é utilizada só por nós?

Fiquei pensando se isso não deveria ser configurável, mas vi que tudo atualmente está chapado nela, então de boa

2020-05-28 02:33 UTC, foolOnTheHill commented on fcm.go
> +			MaxConnsPerHost:     0,
Pra não ter limite [[1](https://golang.org/src/net/http/transport.go)]

```
	// MaxConnsPerHost optionally limits the total number of
	// connections per host, including connections in the dialing,
	// active, and idle states. On limit violation, dials will block.
	//
	// Zero means no limit.// MaxConnsPerHost optionally limits the total number of
	// connections per host, including connections in the dialing,
	// active, and idle states. On limit violation, dials will block.
	//
	// Zero means no limit.
```

2020-05-28 02:34 UTC, foolOnTheHill commented on fcm.go
> +		Timeout: 1 * time.Second,
Acho que só a gente que usa :thinking:

2020-05-28 02:35 UTC, ottony commented on fcm.go
> +		Timeout: 1 * time.Second,
Blz

2020-05-28 02:36 UTC, ottony approved these changes

2020-05-28 13:36 UTC, tonidas commented on fcm.go
> +			MaxIdleConns:        0,
Isso aqui significa que a aplicação está propensa a estourar memória com conexões idle.
Acho que o cenário ideal é colocar um limite e monitorar de alguma forma esse cliente (métricas!) pra ver se ele está dropando mtas conexões.

2020-05-28 13:37 UTC, tonidas commented on fcm.go
> +			MaxConnsPerHost:     0,
Essa config é muito legal pra não fazer com que um host estrague a festa toda. Vc pode deixar essa config ativa e a de cima desativada!

2020-05-29 15:35 UTC, foolOnTheHill commented on fcm.go
> +			MaxIdleConns:        0,
É possível add essas métricas de conexões criadas / reusadas, acham que há problema em expor isso mesmo numa lib? @racevedoo @tonidas @figueredo @ottony

2020-05-29 19:50 UTC, racevedoo requested changes

2020-05-29 19:50 UTC, racevedoo commented on fcm.go
> +		Timeout: 1 * time.Second,
@foolOnTheHill ainda acho que isso devia ser configurável, talvez até deixando quem usa a lib passar o próprio http.Client

2020-05-29 19:50 UTC, racevedoo commented on fcm.go
> +		Timeout: 1 * time.Second,
pode ser que no 4apps a gnt queira uma config diferente dependendo do serviço que estamos batendo

2020-05-29 20:20 UTC, foolOnTheHill commented on fcm.go
> +		Timeout: 1 * time.Second,
@racevedoo mas esse é um cliente pro Firebase, especificamente, usado no push svc. Tu enxerga ele sendo usado em outro serviço?

2020-06-01 18:09 UTC, tonidas approved these changes

2020-06-03 21:23 UTC, figueredo approved these changes

2020-06-05 13:04 UTC, racevedoo approved these changes

2020-06-05 13:08 UTC, merged